### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by ghost** [nanochess/bootRogue#1]
Hi,

Thanks for this, it's impressive how you squashed a playable game into 512 bytes! Just a few questions and comments after completing the game.

1. Seems like armour and health always spawn in pairs like this:

```
.........  
...X.X...
.........
```

Is that intentional?

2. On one level, I think I spawned on top of a monster which was a bit confusing

3. Seems like gold doesn't have a purpose?

4. If you could find a way to fit them, indicators for dungeon level, armor and weapon level would improve the game a lot in my opinion. Even if you drop gold or some other features :)

5. On the way out of the dungeon with the amulet, it seems like my armor was so strong that no monster could hurt me. Maybe that's your intention though :)

Thanks again.

**Comment by nanochess** [comment]
Hi.

1. The random number generator is guilty of this pattern.
2. It's because the level is filled before start, but no check is done when placing player.
3. Only to make it nicer.
4. It's pretty hard, each of these features would take at least 8 bytes.
5. Not my intention but there are no detailed armor/weapons, these only increase and there's no limit to their appearance.

Thanks!

**Comment by ghost** [comment]
Thanks for the explanations, feel free to close the issue if you prefer :)
